# Generated by Django 5.2.10 on 2026-01-15 18:31

import converter.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to=converter.models.upload_to_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=10)),
                ('converted_file', models.FileField(blank=True, null=True, upload_to=converter.models.converted_file_path)),
                ('markdown_content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('converting', 'Converting'), ('converted', 'Converted'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversion_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='converter.conversionbatch')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
